site_name: OntologyBrowser Docs
theme:
  name: material
  palette:
    scheme: default
    primary: teal
    accent: green
  features:
    - navigation.sections
    - navigation.path
    - navigation.indexes
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - attr_list
  - md_in_html
plugins:
# https://github.com/lukasgeiter/mkdocs-awesome-nav
  - search
  - awesome-nav